Allow transcribing of zero nodes in certain cases
Rust-GCC/gccrs pull request #1071
Opened 2022-03-29 08:16 UTC by CohenArthur

When expanding AST fragments containing multiple nodes, we must be aware
that some cases allow expanding zero or more nodes. Any macro
transcription that gets parsed as many nodes (ie any transcriber function that calls `parse_many`) needs to be able to parse zero of those nodes and still get expanded properly (basically, removed).

Previously, this would cause a failure to lower the macro invocation which would remain as a child instead of getting stripped/erased.

2022-03-30 09:05 UTC, philberty requested changes
I think the is_one_node flag needs looked at here.

If this is to handle a case where its an empty macro invocation but still needs to transcribe it could be a special flag like is_empty_macro because its too confusing with nodes.size() == 1 here.

Or as a last resort a comment surrounding the flag field. Though I still think we need to change that name.

2022-03-30 09:05 UTC, philberty commented on gcc/rust/ast/rust-ast.h
> +  bool is_one_node () const { return fragment_is_one_node; }
does this need to be a flag? What about nodes.size() == 1?

2022-03-30 09:05 UTC, philberty commented on gcc/rust/ast/rust-ast.h
> +      return nodes.size () == 1;
this seems confusing to me. If we can remove the flag then I think this is fine. But I might be missing something going on. Is this a flag to say its an empty macro invocation but we need to still transcribe? if ```!nodes.empty()```

2022-03-31 08:26 UTC, CohenArthur commented
@philberty you're right about the flag, it was not necessary. I was trying to still have the possibility to create empty AST fragments and have them be an error sometimes, but it's not necessary. So simply removing the flag and the extra code to handle this special case works perfectly. Sorry about that!

2022-03-31 09:56 UTC, CohenArthur commented
bors r+

2022-03-31 10:23 UTC, merged