transmute: Fix behavior by always performing the raw copy
Rust-GCC/gccrs pull request #1452
Opened 2022-08-09 12:39 UTC by CohenArthur

This desugars calls to transmute the following way:

`transmute::<T1, T2>(value)`

->

`*((T2 *) &value)`

This always ends up being optimized into a simple copy for small types
and a memcpy for larger types.

2022-08-09 14:00 UTC, philberty requested changes
Nice work.

IIRC the test here is likely to fail on the build farm it might be worthwhile chaning to use i32 seems to be more portable when printing stuff like this.

Or maybe instead we do dg-scan-gimple for the transmute stuff I think there are some examples in the testsuite for that.

2022-08-10 07:20 UTC, CohenArthur commented
> Nice work.
> 
> IIRC the test here is likely to fail on the build farm it might be worthwhile chaning to use i32 seems to be more portable when printing stuff like this.

I've changed the test to not print anything and be more minimal. It's also using 32 bit values now to be sure :)

> Or maybe instead we do dg-scan-gimple for the transmute stuff I think there are some examples in the testsuite for that.

I think this is harder, and I didn't want to lose too much time fighting dejagnu haha. Ideally, what this testcase should simply test is that raw integer types have the same behavior as ADT-like types when transmuting, as that behavior was already the correct one.

2022-08-10 09:57 UTC, philberty approved these changes
LGTM

2022-08-10 10:04 UTC, CohenArthur commented
Waiting for #1454 because I think there'll be merge conflicts

2022-08-10 10:34 UTC, CohenArthur commented
bors r+

2022-08-10 11:06 UTC, merged