Change how CompileVarDecl outputs Bvariable's
Rust-GCC/gccrs pull request #1736
Opened 2023-01-11 17:10 UTC by powerboat9

This allows patterns to declare multiple/no variables

Signed-off-by: Owen Avery <powerboat9.gamer@gmail.com>
---

2023-01-12 09:11 UTC, CohenArthur reviewed
Code wise this looks good to me apart from the raw pointer. Waiting for Philip's review as he knows more about this part of the project

2023-01-12 09:11 UTC, CohenArthur commented on gcc/rust/backend/rust-compile-var-decl.h
> +		       std::vector<Bvariable *> *locals, Context *ctx)
How about passing a reference here?
```suggestion
		       std::vector<Bvariable *> &locals, Context *ctx)
```

2023-01-12 09:11 UTC, CohenArthur commented on gcc/rust/backend/rust-compile-var-decl.h
> +		  std::vector<Bvariable *> *locals)
Same here

2023-01-12 09:11 UTC, CohenArthur commented on gcc/rust/backend/rust-compile-var-decl.h
> +  std::vector<Bvariable *> *locals;
And then keep a reference here instead :)
```suggestion
  std::vector<Bvariable *> &locals;
```

2023-01-12 18:22 UTC, philberty reviewed
I've been spending a good bit of time writing and rewriting my thoughts on this grouped pattern support. I think it depends on understanding the rustc behaviour from my side better.

I think the question is when we restructure:

```
a, b = (123, 456)
```

Is a and b a copy of the fields or do the reference the fields? My initial thoughts here are that a,b should be field access expressions and not stack variables, so that they reference the structure storage itself and avoid copying.

Maybe @flip1995 can help answer that for me. If we can figure out what the behaviour is it determines the approach here.

If we go with this approach, we are going to be taking copy's and offloading the destructure logic to the assignment, or we can treat a,b as a special grouped variable so the assignment does not create two new variables but we reuse the pattern binding code from our match expression which then any reference to a or b we actually get back field access expressions. 

I will try and write some rustc examples to figure this out later as well.

# TLDR

So from C perspective is this:

```rust
let a,b = (123, 456);
let c = a + b;
```

solution A:

```c
struct Foo { 
  i32 x;
  i32 y;
}

struct Foo tmp = Foo(123, 456);
i32 a = tmp.0;
i32 b = tmp.1;
i32 c = a + b;
```

This means we get real variables and this patch is the right approach but means we are taking copys.

solution B

```c
struct Foo { 
  i32 x;
  i32 y;
}

struct Foo tmp = Foo(123, 456);
i32 c = tmp.0 + tmp.1;
```

This looses debug info but means a,b just reuse the same storage.

2023-01-12 18:39 UTC, philberty commented
Ok it looks like it is infact copy's https://godbolt.org/z/eh93YoYT4

2023-01-12 18:41 UTC, philberty requested changes
Ok I think I will be happy with this once you fix up @CohenArthur 's comments. We use references where possible.

2023-01-13 02:55 UTC, powerboat9 commented
Checks are failing because of dependency downloading errors.

2023-01-13 09:33 UTC, flip1995 commented
Unlike whatever C++ does with structured bindings ([really weird behavior](https://stackoverflow.com/questions/46114214/lambda-implicit-capture-fails-with-variable-declared-from-structured-binding)), in Rust 

```rust
let t = (123, 456);
let (a, b) = t;
```

Is the same as 

```rust
let a = t.0;
let b = t.1;
```

I would assume, that if you compile in release mode or with `-O`/`-Copt-level=3` the copies are optimized away.

2023-01-13 11:40 UTC, CohenArthur approved these changes
LGTM :) I asked the CI to re-run on failed jobs but this should not be a problem

2023-01-13 15:20 UTC, philberty commented
Just checking CI is good.

2023-01-13 15:20 UTC, philberty approved these changes
Good job thanks for working through this with us!

2023-01-14 22:35 UTC, philberty commented
bors r+

2023-01-14 23:20 UTC, merged