Support for TuplePattern in let statements
Rust-GCC/gccrs pull request #1820
Opened 2023-02-02 19:12 UTC by powerboat9

2023-02-03 11:38 UTC, CohenArthur reviewed
Code looks good to me :) thanks!

2023-02-03 11:38 UTC, CohenArthur commented on gcc/rust/backend/rust-compile-pattern.cc
> +			"ranged tuple pattern in let statement");
Is this something we cannot compile yet but that should be allowed? In which case, 
```suggestion
      rust_sorry_at (pattern.get_locus (),
			"ranged tuple pattern in let statement");
```
if not, why is it a fatal_error and not a regular error? Is it a compiler error to have a ranged pattern in a tuple pattern, as if "did something go wrong earlier in gccrs to get to that point"? In that case, we should have an assertion failure IMO

2023-02-03 11:38 UTC, CohenArthur commented on gcc/rust/backend/rust-compile-pattern.cc
> +  rust_assert (!ty->is_unit ());
Note that
```rust
fn main() {
    let () = ();
}
```
is valid Rust but we cannot parse it yet. It'd be nice to have a TODO or FIXME here and open up an issue (which I can do if you want)

2023-02-04 22:49 UTC, philberty requested changes
Minor nit on the switch statement, I would like to see two things:

1. Test case involving using the bindings of the pattern.

```
fn main () -> i32 {
  let (a,b) = (1,2)
  a + b - 3
}
```

So it ensures this should return 0.

- This is probably better as another commit/pr how do we handle when the number of elements in the pattern do not match the initilizer.

````let (a,b) = (1,2,3,4,5,6).```

I would be happy to merge if you fix the style nit in the switch statement and add usage of a binding in the test case.

2023-02-04 22:49 UTC, philberty commented on gcc/rust/backend/rust-compile-pattern.cc
> +      gcc_unreachable ();
I dont't like default being at the start of a switch

2023-02-05 03:57 UTC, powerboat9 commented
Requested changes are implemented, though element number mismatches and usages of RestPattern throw ICEs.

2023-02-05 18:45 UTC, philberty requested changes
LGTM but you need to rebase this into 1 commit. Great work thanks for updating the test case please raise issues about the ICE when you get a chance

2023-02-08 10:43 UTC, CohenArthur commented
Looks good thank you :) bors r+

2023-02-08 10:43 UTC, CohenArthur commented
Oops forgot bors needs a newline

bors r+

2023-02-10 11:40 UTC, CohenArthur commented
bors r+

2023-02-10 12:19 UTC, merged