Move expr into base class ExprStmt
Rust-GCC/gccrs pull request #1827
Opened 2023-02-05 01:29 UTC by powerboat9

Moves some of the functionality of HIR::ExprStmtWith{,out}Block into HIR::ExprStmt.

Signed-off-by: Owen Avery <powerboat9.gamer@gmail.com>

2023-02-05 08:40 UTC, CohenArthur approved these changes
The code changes look good to me. Any reason why you moved the expr inside `ExprStmt` rather than `ExprStmtWith{,out}Block`? Just refactoring?

2023-02-05 15:43 UTC, powerboat9 commented
Refactoring, with an end goal of replacing HIR::ExprStmtWith{,out}Block with HIR::ExprStmt.

2023-02-05 18:37 UTC, philberty commented
I am anxious about making this change to HIR before we fix the block expression issue within the AST do we have an open issue for that on @CohenArthur ?

2023-02-05 18:41 UTC, philberty commented
Here it is: https://github.com/Rust-GCC/gccrs/issues/1253 we should fix this first, if we change the HIR structure before the AST is fixed here we might end up in a situation where we need to revert this change and do it again to fit the model that was used to first the issue in the AST

2023-02-05 18:42 UTC, philberty requested changes
I am not in favour of this change until https://github.com/Rust-GCC/gccrs/issues/1253 is fixed

2023-02-06 05:20 UTC, powerboat9 commented
I'm not sure how unifying HIR::ExprStmt.* would interfere with solving #1253. If anything, it seems like it would make the eventual solution more simple. Regardless, this doesn't actually unify HIR::ExprStmt.*, its just a refactor.

2023-02-06 21:00 UTC, philberty commented
@powerboat9  I understand, but from my experince here there is a risk that we end up fixing that issue with block expression and tail expression handling in the AST which might cause quite a few changes to the HIR expression handling which might just negate your change here. I think we should avoid changing Stmt and Expression's until we are happy with block expressions, which have been notoriously tricky to get 100% correct.

2023-02-16 11:18 UTC, CohenArthur commented
@powerboat9 I agree with @philberty here. I think we might end up in a situation where that part of the HIR changes so much from fixing #1253 that theses changes will be void or hinder us. Sorry

2023-02-16 16:50 UTC, philberty commented
Sorry @powerboat9 I am going to close this PR and we can revisit this down the line when we fix the block expression issues like #1253 and https://github.com/Rust-GCC/gccrs/issues/413

2023-02-16 16:50 UTC, closed without merging