Fix `FeatureGate::gate` will crash on 32-bit x86.
Rust-GCC/gccrs pull request #1956
Opened 2023-03-02 02:40 UTC by TuringKi

gcc/rust/ChangeLog:

	* checks/errors/rust-feature-gate.cc: fix 'ld'->'lu'.

2023-03-02 11:31 UTC, tschwinge requested changes
The issue isn't with `signed` vs. `unsigned`, but rather the size of the data, per my understanding; see <https://github.com/Rust-GCC/gccrs/issues/1952#issuecomment-1451719409>.

2023-03-14 15:18 UTC, CohenArthur approved these changes
This looks good to me :) But we'll need to have a think about it when https://github.com/rust-lang/rust reaches its 4294967295th issue... :D

2023-03-20 21:14 UTC, philberty approved these changes
LGTM

2023-03-20 21:15 UTC, philberty commented
@tschwinge poke, or should we just make this an unsigned?

2023-03-20 21:36 UTC, tschwinge commented
As I don't seem to get my message across in the #1952 discussion, that we really ought to use plain `unsigned` for `%u` format string, I've now amended the original commit with that change, and force-pushed.

2023-03-20 23:18 UTC, merged

2023-03-21 08:33 UTC, tschwinge commented
:+1: "A restored build has been detected on builder gccrust-debian-i386", <https://inbox.sourceware.org/gcc-rust/20230320232827.8A9773858D32@sourceware.org>.