Fix Bad formatting in AST expanded dump with associated types
Rust-GCC/gccrs pull request #2122
Opened 2023-04-13 13:28 UTC by ArberSephirotheca

gcc/rust/ChangeLog:

        * ast/rust-ast-dump.cc: implement visit() function for QualifiedPathInType. Fixed bad formatting of type alias in ast dump.

Fixes #2023

2023-04-14 10:33 UTC, CohenArthur approved these changes
Can you provide the output of the dump when running it on the code in the issue you linked? This way we'll see how it looks. I think this is great otherwise :)

2023-04-14 10:33 UTC, CohenArthur commented on gcc/rust/ast/rust-ast-dump.cc
> +  stream << "::";
```suggestion
  stream << ">::";
```

2023-04-15 07:51 UTC, ArberSephirotheca commented
> Can you provide the output of the dump when running it on the code in the issue you linked? This way we'll see how it looks. I think this is great otherwise :)

No problem!

2023-04-15 10:16 UTC, P-E-P requested changes
I would like a few changes related to this settings file, otherwise the changes are good and I will be glad to approve this PR.

2023-04-15 13:24 UTC, ArberSephirotheca commented on gcc/rust/.vscode/settings.json
> +{
> I'm not sure this config files fits at this location nor in this PR. I'm not entirely sure about it, but `$ROOT_GCC/contrib` may be better ?

This file is unrelated to this PR and is push by me accidently.. Sorry for the confusion and feel free to delete that file.

2023-04-17 12:17 UTC, CohenArthur approved these changes
Looks good to me :) Thanks!

2023-04-17 12:17 UTC, CohenArthur commented on gcc/rust/ast/rust-ast-dump.cc
> +	 << "\n";
Same, here you can just merge the two strings
```suggestion
  stream << ";\n";
```

2023-04-17 13:38 UTC, P-E-P approved these changes

2023-04-19 11:14 UTC, CohenArthur approved these changes
Great work! Thank you!

2023-04-19 21:13 UTC, philberty approved these changes
LGTM

2023-04-20 08:37 UTC, merged