Handle keywords in macro fragments
Rust-GCC/gccrs pull request #2200
Opened 2023-05-09 01:09 UTC by powerboat9

Fixes #2192

2023-05-09 08:46 UTC, philberty requested changes
This looks good to me just a small nit with the naming of that helper. Other wise great job!

2023-05-09 08:46 UTC, philberty commented on gcc/rust/parse/rust-parse-impl.h
> +Parser<ManagedTokenSource>::is_ident_like_tk (TokenId id)
I think is_keyword_token would be a better name

2023-05-10 06:12 UTC, powerboat9 commented
Renamed to ```is_keyword_or_ident_token```since it also matches identifiers

2023-05-10 08:30 UTC, CohenArthur reviewed
Looks good to me, just wondering about the public parsing function you introduced - we can name it `parse_ident_token` instead and it would be clearer IMO.

2023-05-12 11:28 UTC, CohenArthur approved these changes

2023-05-12 12:19 UTC, merged