Handle keyword metavariables during macro expansion
Rust-GCC/gccrs pull request #2221
Opened 2023-05-16 17:31 UTC by powerboat9

Fixes #2194

2023-05-17 16:19 UTC, philberty requested changes
Hmmm I think this LGTM but just wondering if get_str_handle_keyword should just replace the get_str function? I think the only reason get_str dodesnt work is jsut because any keyword has a null token but has a token id set and this fixes it. I wonder can you check that?

Otherwise i think the get_str and get_str_handle_keyword just seems confusing.

2023-05-17 16:49 UTC, powerboat9 commented
Should be fixed now

2023-05-18 16:39 UTC, philberty commented on gcc/rust/expand/rust-macro-substitute-ctx.cc
> +    goto case_keyword;
do you need this goto? 

I wonder can you turn the case IDENTIFIER into the default case and leave the case LEFT_PAREN as is?

2023-05-18 16:39 UTC, philberty commented
Also thanks for fixed the get_str is looking brilliant

2023-05-18 17:50 UTC, powerboat9 commented
```goto``` removed

2023-05-18 20:29 UTC, CohenArthur approved these changes
LGTM

2023-05-18 21:12 UTC, merged