Fix warning generated by Optional
Rust-GCC/gccrs pull request #2269
Opened 2023-06-05 16:11 UTC by powerboat9

This should fix #2242. Can someone trigger the bootstrap CI to verify?

2023-06-05 16:14 UTC, CohenArthur commented
@powerboat9 you get different errors now (running the bootstrap locally):

```rust
In file included from ../../gcc/rust/util/rust-hir-map.h:22,
                 from ../../gcc/rust/ast/rust-ast.h:24,
                 from ../../gcc/rust/ast/rust-ast-full.h:22,
                 from ../../gcc/rust/ast/rust-ast-formatting.cc:20:
../../gcc/rust/util/rust-optional.h: In instantiation of ‘Rust::Optional<T>::Optional(const Rust::Optional<T>&) [with T = Rust::BuiltinMacro]’:
../../gcc/rust/ast/rust-macro.h:682:61:   required from here
../../gcc/rust/util/rust-optional.h:101:21: error: assignment of member ‘Rust::Optional<Rust::BuiltinMacro>::<unnamed union>::value’ in read-only object
  101 |         other.value = other.value;
      |         ~~~~~~~~~~~~^~~~~~~~~~~~~
In file included from ../../gcc/rust/util/rust-hir-map.h:22,
                 from ../../gcc/rust/ast/rust-ast.h:24,
                 from ../../gcc/rust/ast/rust-macro.h:23,
                 from ../../gcc/rust/ast/rust-macro.cc:19:
../../gcc/rust/util/rust-optional.h: In instantiation of ‘Rust::Optional<T>::Optional(const Rust::Optional<T>&) [with T = Rust::BuiltinMacro]’:
../../gcc/rust/ast/rust-macro.h:682:61:   required from here
```

2023-06-05 19:59 UTC, powerboat9 commented
Ok, if [this](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80635#c53) is accurate, this commit should fix it

2023-06-06 03:33 UTC, powerboat9 commented
Checking bootstrap using https://github.com/powerboat9/gccrs/actions/runs/5183710370/jobs/9341907906

2023-06-06 12:38 UTC, CohenArthur commented
Built locally and it does work @powerboat9 :+1:

2023-06-06 12:39 UTC, CohenArthur requested changes

2023-06-06 12:39 UTC, CohenArthur commented on gcc/rust/util/rust-optional.h
> +    volatile char unused;
Please add a comment explaning the fix and linking the issue you put in your github comment. We also need a `FIXME: Remove this` so we remember to get to it

2023-06-06 14:38 UTC, CohenArthur approved these changes

2023-06-06 15:51 UTC, merged