Move ast collector template implementation to header file
Rust-GCC/gccrs pull request #2286
Opened 2023-06-12 07:56 UTC by SainiAditya1

Thank you for making Rust GCC better!

If your PR fixes an issue, you can add "Fixes #issue_number" into this
PR description and the git commit message. This way the issue will be
automatically closed when your PR is merged. If your change addresses
an issue but does not fully fix it please mark it as "Addresses #issue_number"
in the git commit message.

Here is a checklist to help you with your PR.

- \[ ] GCC development requires copyright assignment or the Developer's Certificate of Origin sign-off, see https://gcc.gnu.org/contribute.html or https://gcc.gnu.org/dco.html
- \[ ] Read contributing guidlines
- \[ ] `make check-rust` passes locally
- \[ ] Run `clang-format`
- \[ ] Added any relevant test cases to `gcc/testsuite/rust/`

Note that you can skip the above if you are just opening a WIP PR in
order to get feedback.
---

*Please write a comment explaining your change. This is the message
that will be part of the merge commit.

2023-06-12 14:30 UTC, CohenArthur approved these changes

2023-06-12 14:31 UTC, CohenArthur commented
Oh, @SainiAditya1: you'll also need to remove the implementation from `rust-ast-collector.cc`

2023-06-12 14:31 UTC, SainiAditya1 commented
@CohenArthur sure , I will remove .

2023-06-13 12:23 UTC, P-E-P requested changes
There are some modifications required for the code to successfully pass the ci:
- the code should compile, this could be easily fixed by adding back the default argument values
- the code should be correctly formatted
- every commit should compile independently. I suggest you squash all your commits together. It doesn't really matter if your commits are not atomic since gcc has a long tradition of monstrously large commits.

Keep the good work, it may seems tedious but you're not that far!

2023-06-13 12:23 UTC, P-E-P commented on gcc/rust/ast/rust-ast-collector.h
> -					size_t end_offset = 0);
You need to keep default arguments, those are used in the visitor in many situations, removing them means the code won't compile correctly.

2023-06-13 12:23 UTC, P-E-P commented on gcc/rust/ast/rust-ast-collector.h
> +			     TokenId right_brace )
Same thing here, we need to keep those default values.

2023-06-13 12:23 UTC, P-E-P commented on gcc/rust/ast/rust-ast-collector.h
> +  }
I may be wrong but this part does not look correctly formatted ?

2023-06-13 12:23 UTC, P-E-P commented on gcc/rust/ast/rust-ast-collector.h
> +  void visit_as_line (T &item, std::vector<TokenPtr> trailing )
We need to keep the empty vector default value.

2023-06-20 08:11 UTC, philberty commented
@SainiAditya1 you need to rebase your PR against master then fix the commit format and code formatting before we can merge this

2023-06-23 12:43 UTC, SainiAditya1 commented
@philberty

2023-06-27 09:33 UTC, philberty commented
@SainiAditya1 your git commit messages are failing:

Checking 317c20c22bd0c943d59366c6c1ac8b5ff23a8882: OK
Checking b2e5dd04ea85d1db626d71424648e920263a2298: FAILED
ERR: cannot find a ChangeLog location in message
Checking c89a5b2eea37549eb4532b5eaba3c1842969faca: OK
Checking 7ddce9078a36e0bbcc08f5c28b400dff0e28d7d0: FAILED
ERR: cannot find a ChangeLog location in message

2023-06-27 09:33 UTC, philberty commented on Makefile.def
> -dependencies = { module=all-gcc; on=all-libgrust; };
I dont think this should have changed this was a fix for parallel builds

2023-06-27 09:33 UTC, philberty commented on Makefile.in
> -all-gcc: maybe-all-libgrust
this is unrelated change

2023-06-27 09:33 UTC, philberty commented on configure
> -# Disable libgrust when not using the rust language
same

2023-06-27 09:34 UTC, philberty commented on configure.ac
> -# Disable libgrust when not using the rust language
same

2023-06-27 09:34 UTC, philberty commented on gcc/testsuite/rust/compile/issue-2019-2.rs
> -pub trait Add<RHS = Self> {
Why are you deleting this?

2023-06-27 09:43 UTC, philberty commented
Hi @SainiAditya1, I am going to close this PR as it's very far off course from the initial issue and the deletion of this many test cases and build system changes are not correct.

I suggest starting from a fresh branch and making a new PR.

2023-06-27 09:43 UTC, closed without merging