Add `ForeverStackStore`
Rust-GCC/gccrs pull request #3251
Opened 2024-11-15 01:05 UTC by powerboat9

ForeverStackStore is meant to partially unify the internal states of per-namespace ForeverStack instances. This PR doesn't contain modifications to ForeverStack which would allow it to rely on a ForeverStackStore to store nodes, but a future PR should address this.

2024-11-25 19:35 UTC, powerboat9 commented
@CohenArthur @P-E-P @philberty thoughts?

2024-11-25 20:49 UTC, P-E-P commented
> @CohenArthur @P-E-P @philberty thoughts?

I'm mostly fine with this idea, but I've not finished reviewing it entirely yet.

2024-11-26 17:27 UTC, P-E-P approved these changes
It looks good, although I'd like @CohenArthur to review this PR because he's the one who brought `ForeverStack` in the first place and should have a better insight.

2024-11-27 16:52 UTC, philberty requested changes
I have style nits but up to @CohenArthur on that one or @tschwinge  or @dkm  to make it GCC Style

2024-11-27 16:52 UTC, philberty commented on gcc/rust/resolve/rust-forever-stack.cc
> +    return tl::nullopt;
This is such a small nit i have I prefer the style:

```
if (parent)
  return xyz;
  
return tl::nullopt;
```

or :

```
return parent ? *parent : tl::nullopt;
```

2024-11-28 11:52 UTC, CohenArthur requested changes
I'm not against the PR, I think the code looks good but I am having a hard time wrapping my head around how this could be used. @powerboat9 could you do one big PR containing the `ForeverStackStore` and the usage of it by `ForeverStack`? I feel like it would help me a lot.

2024-11-28 11:53 UTC, CohenArthur commented
Actually nevermind my comment I just saw you had submitted #3258 as well - I'll review it and then come back to this PR. apologies for the hasty review

2024-11-30 01:41 UTC, powerboat9 commented on gcc/rust/resolve/rust-forever-stack.cc
> +  while (true)
Yeah, `lambda () == KeepGoing::Yes` should probably just be the loop condition

2024-11-30 02:20 UTC, powerboat9 commented on gcc/rust/resolve/rust-forever-stack.cc
> +  while (true)
I've tweaked it to use a for loop now -- the condition is a bit odd, but it should be succinct

2024-11-30 02:20 UTC, powerboat9 commented on gcc/rust/resolve/rust-forever-stack.cc
> +  rust_unreachable ();
Willing to change it if it's a deal breaker, though

2024-12-09 13:13 UTC, CohenArthur approved these changes
LGTM! if everything @philberty had to say is resolved, then I'm happy to merge this

2024-12-14 04:01 UTC, powerboat9 commented
@philberty ?

2024-12-27 18:25 UTC, powerboat9 commented on gcc/rust/resolve/rust-forever-stack.cc
> +  rust_unreachable ();
On second thought, seems like a small improvement

2025-01-10 12:58 UTC, philberty approved these changes
LGTM

2025-01-10 13:25 UTC, merged