Changes made to ensure that '=>' token is parsed properly
Rust-GCC/gccrs pull request #3292
Opened 2024-12-04 17:49 UTC by sriganeshres

gcc/rust/ChangeLog:

	* parse/rust-parse-impl.h (Parser::parse_expr): (Parser::left_denotations): (Parser::null_denotation):
	* parse/rust-parse.h (struct ParseRestrictions):

Thank you for making Rust GCC better!

Fixes #3099 
Here is a checklist to help you with your PR.

- \[x] GCC development requires copyright assignment or the Developer's Certificate of Origin sign-off, see https://gcc.gnu.org/contribute.html or https://gcc.gnu.org/dco.html
- \[x] Read contributing guidlines
- \[x] `make check-rust` passes locally
- \[ ] Run `clang-format`
- \[ ] Added any relevant test cases to `gcc/testsuite/rust/`

* I have made chnages to 3 functions `Parser::parse_expr`, `Parser::left_denotations`, `Parser::null_denotation` So that they stop on special token like `=>` and `,`.  They would terminate the parsing to allow exatract expression.

2024-12-04 17:53 UTC, CohenArthur reviewed
Thanks @sriganeshres for contributing!! Could you add a testcase to your PR to ensure we don't introduce a regression on this in the future?

2024-12-04 18:36 UTC, sriganeshres commented
> Thanks @sriganeshres for contributing!! Could you add a testcase to your PR to ensure we don't introduce a regression on this in the future?

Working on that. I have ran `make check-rust` it gave correct results. Can you give me an idea of what type of test to be written for this. 

Thank You.

2024-12-09 15:33 UTC, P-E-P commented
> Working on that. I have ran `make check-rust` it gave correct results. Can you give me an idea of what type of test to be written for this.

You could write a test from the snippet given in the fixed issue, it would pass with your changes

2024-12-12 15:41 UTC, philberty commented on gcc/rust/parse/rust-parse.h
> +    = false; // This is for stopping parsing at a specific token
What does this mean? It seems like a hack

2024-12-12 15:43 UTC, philberty requested changes
This doesnt seem correct to me the stop_on_token doesn't seem to be set to true anywhere so to me this doesn't seem to solve anything

2024-12-27 08:32 UTC, badumbatish requested changes

2024-12-27 08:32 UTC, badumbatish commented on gcc/testsuite/rust/compile/issue-3099.rs
> +        let format = "Result: %d\n\0" as *const str as *const i8;
hi @sriganeshres, make sure that you also update your dejagnu regex to assert that you'll get out 15 from println!. 

Without asserting the printf, you're just guarantee that we at least parse it successfully

2024-12-27 08:32 UTC, badumbatish commented on gcc/testsuite/rust/compile/issue-3099.rs
> +    unsafe {
is the unsafe necessary?

2024-12-27 08:32 UTC, badumbatish commented on gcc/rust/parse/rust-parse-impl.h
> +      if (restrictions.stop_on_token && (id == MATCH_ARROW || id == COMMA))
you're not setting stop_on_token to true so you're not entering these conditional either.

2024-12-27 08:32 UTC, badumbatish commented on gcc/rust/parse/rust-parse-impl.h
> +	      || current_token->get_id () == COMMA))
this seems weird. you'd want to enter left denotation and create the infix with =>

2025-01-02 09:42 UTC, CohenArthur commented on gcc/testsuite/rust/compile/issue-3099.rs
> +    unsafe {
it's necessary for the `printf` call, but not before - so it could be moved down a few lines indeed

2025-04-18 10:42 UTC, closed without merging