Add type check on if-expr
Rust-GCC/gccrs pull request #3306
Opened 2024-12-16 13:24 UTC by Kamiinarii78

Check if an if-expr return void type.

gcc/rust/ChangeLog:

	* typecheck/rust-hir-type-check-expr.cc (TypeCheckExpr::visit): Add check on if-expr.

gcc/testsuite/ChangeLog:

	* rust/compile/implicit_returns_err3.rs: Change test to be valid.
	* rust/compile/torture/if.rs: Likewise.
	* rust/compile/if-without-else.rs: New test.

Fixes: #3230

2024-12-18 10:10 UTC, CohenArthur approved these changes
I think this is good, thank you!! Just waiting on Philip to check it as he knows the typechecker :D

2025-01-10 09:09 UTC, philberty approved these changes
LGTM

2025-01-10 12:53 UTC, philberty requested changes
This is now rebased and looks like there are failing tests can you investigate?

2025-02-04 12:54 UTC, philberty reviewed
I think this LGTM but i would prefer if we use the result of the coercion_site if that works if not then let us know and we can go with this.

Also we really need to make an issue about making much nicer helpers for looking up those builtin types

2025-02-17 10:05 UTC, merged