refactor all attribute functions in rust-compile-base.cc
Rust-GCC/gccrs pull request #3336
Opened 2024-12-31 17:15 UTC by saeitoshi-10

gcc/rust/ChangeLog:
        * backend/rust-compile-base.cc (get_attributes):removed checker function (get_trait_name):removed checker function
	* util/rust-attributes.cc (Attributes::get_attributes):added checker function (Attributes::get_trait_name): added checker function
	* util/rust-attributes.h: added functions definitions in the header file for access

Thank you for making Rust GCC better!

If your PR fixes an issue, you can add "Fixes #issue_number" into this
PR description and the git commit message. This way the issue will be
automatically closed when your PR is merged. If your change addresses
an issue but does not fully fix it please mark it as "Addresses #issue_number"
in the git commit message.

Here is a checklist to help you with your PR.

- \[ ] GCC development requires copyright assignment or the Developer's Certificate of Origin sign-off, see https://gcc.gnu.org/contribute.html or https://gcc.gnu.org/dco.html
- \[ ] Read contributing guidlines
- \[ ] `make check-rust` passes locally
- \[ ] Run `clang-format`
- \[ ] Added any relevant test cases to `gcc/testsuite/rust/`

Note that you can skip the above if you are just opening a WIP PR in
order to get feedback.
---
Fixes : #3291 
*Please write a comment explaining your change. This is the message
that will be part of the merge commit.

2025-01-01 03:11 UTC, saeitoshi-10 commented
no i didn't see any other implementations till but if it exists i'll be sure to replace that

2025-01-10 11:31 UTC, philberty reviewed
This seems fine but not 100% sure probably best to ask @P-E-P iirc did this code sometimes its useful to keep stuff thats associated local i am fine with it if others are

2025-01-10 13:21 UTC, philberty commented
@saeitoshi-10 merge conflicts this needs rebased

2025-01-16 15:11 UTC, P-E-P commented on gcc/rust/util/rust-attributes.h
> +  static std::string get_trait_name (const AST::Attribute &attr);
I'm not keen to adding those functions in the attribute class as here attribute means two different things. The first one is the attribute as we all know it in rust `#[attribute]` (1), but the second one is specific to proc macros (2). On one hand moving it inside the attribute class seems appropriate because it is indeed part of proc macro declaration which are attributes(1) but on the other hand it might confuse people as it really only works for (2)

2025-01-16 15:18 UTC, P-E-P requested changes
You need to amend your commit message. Right now you've kept the autogenerated commit message which is great. But a commit message should contain more than that.

GCC uses the usual convention that can be found in most projects, one short title (max 50 columns), it should contain keywords to easily identify the commit among others.

Then a blank line.

And then a description about why the commit has been introduced, why it exists and even why those changes are done this way. This section should be wrapped at 72 columns.

Then I usually leave another blank line and keep the generated changelog structure filled with what has been changed.

2025-02-24 09:58 UTC, closed without merging